name: Tests

on:
  push:
    branches:
      - master
      - prod
  pull_request:

jobs:
  warm-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

  build:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Build
        run: pnpm build

  data-schema:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate data schema
        run: pnpm test:data:schema

  data-sanity:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate data sanity
        run: pnpm test:data:sanity

  unit-tests:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Run unit tests
        run: pnpm test:unit

  ui-unit-tests:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Run UI unit tests
        run: pnpm test:ui

  export-schema:
    needs: warm-cache
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate export schema
        run: pnpm test:e2e
