name: Validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

  data-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate data schema
        run: npm run test:data:schema

  data-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate data sanity
        run: npm run test:data:sanity

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Run unit tests
        run: npm run test:unit

  ui-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Run UI unit tests
        run: npm run test:ui

  export-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Shared setup
        uses: $/.github/actions/setup

      - name: Validate export schema
        run: npm run test:e2e
